name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.310
    - name: Install fonts
      run: |
        sudo add-apt-repository ppa:justinabrahms/ttf-cascadia-code
        sudo apt-get update
        sudo apt-get install ttf-cascadia-code
    - name: Install tools
      run: dotnet tool restore
    - name: Build
      run: dotnet cake
