name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.310
    - name: Install fonts
      run: |
        wget "https://github.com/microsoft/cascadia-code/releases/download/v2111.01/CascadiaCode-2111.01.zip"
        unzip CascadiaCode-2111.01.zip
        mkdir -p ~/.local/share/fonts
        cp ./ttf/*.ttf ~/.local/share/fonts
    - name: Install tools
      run: dotnet tool restore
    - name: Build
      run: dotnet cake
